<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>KnouxRepair</AssemblyName>
    <RootNamespace>KnouxRepair</RootNamespace>
    <ApplicationIcon>..\..\assets\KnouxRepair.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <Version>2.0.2</Version>
    <AssemblyVersion>2.0.2.0</AssemblyVersion>
    <FileVersion>2.0.2.0</FileVersion>
    <Company>Knoux</Company>
    <Product>KNOUX Repair</Product>
    <Copyright>Copyright 2026 Knoux. Crafted by Eng. Sadek Elgazar</Copyright>
    <Platforms>x64;AnyCPU</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
  </PropertyGroup>

</Project>
